---
title: "Creating ADaM sets from SDTM"
format: html
---

## Introduction

This document explores the creation of ADaM data sets from raw SDTM files using the [`{admiral}`](https://pharmaverse.github.io/admiral/index.html) R package.

```{r}
#| label: setup
#| include: false
library(dplyr)
library(tidyr)
library(admiral)
library(haven)
library(lubridate)
library(stringr)

data_dir <- "data/sdtm_1000"
```


## ADSL

Let's create an ADSL data set using the guide in the vignette [Creating ADSL](https://pharmaverse.github.io/admiral/articles/adsl.html). First, we import the raw SAS Transport files corresponding to the SDTM data sets:

```{r}
#| label: import_sdtm

dm <- haven::read_xpt(file.path(data_dir, "sas_files", "DM.xpt"))
ds <- haven::read_xpt(file.path(data_dir, "sas_files", "DS.xpt"))
ex <- haven::read_xpt(file.path(data_dir, "sas_files", "EX.xpt"))
ae <- haven::read_xpt(file.path(data_dir, "sas_files", "AE.xpt"))
lb <- haven::read_xpt(file.path(data_dir, "sas_files", "LB.xpt"))

td <- haven::read_xpt(file.path(data_dir, "sas_files", "TD.xpt"))

adsl <- dm
```

Derive/Impute numeric treatment data/time and duration 

```{r}
# impute start and end time of exposure to first and last respectively, do not impute date
ex_ext <- ex %>%
  derive_vars_dtm(
    dtc = EXSTDTC,
    new_vars_prefix = "EXST"
  ) %>%
  derive_vars_dtm(
    dtc = EXENDTC,
    new_vars_prefix = "EXEN",
    time_imputation = "last"
  )

adsl <- adsl %>%
  derive_vars_merged(
    dataset_add = ex_ext,
    filter_add = (EXDOSE > 0 |
      (EXDOSE == 0 &
        str_detect(EXTRT, "PLACEBO"))) & !is.na(EXSTDTM),
    new_vars = vars(TRTSDTM = EXSTDTM, TRTSTMF = EXSTTMF),
    order = vars(EXSTDTM, EXSEQ),
    mode = "first",
    by_vars = vars(STUDYID, USUBJID)
  ) %>%
  derive_vars_merged(
    dataset_add = ex_ext,
    filter_add = (EXDOSE > 0 |
      (EXDOSE == 0 &
        str_detect(EXTRT, "PLACEBO"))) & !is.na(EXENDTM),
    new_vars = vars(TRTEDTM = EXENDTM, TRTETMF = EXENTMF),
    order = vars(EXENDTM, EXSEQ),
    mode = "last",
    by_vars = vars(STUDYID, USUBJID)
  )
```

